### ISSUE TITLE
运行 `ng-alain-plugin-theme -t=colorLess` 发生依赖错误

### ISSUE THREAD

**Issue by rqx110** [ng-alain/plugin-theme#6]
安装：
![image](https://user-images.githubusercontent.com/1829209/205584328-a40567c5-355f-4fd4-a70e-1a4a154ef24c.png)

运行错误:
![image](https://user-images.githubusercontent.com/1829209/205584136-7fb65fc8-4936-4b4a-8db7-87186c4f5058.png)

**Comment by rqx110** [comment]
any news of this?  @cipchk

**Comment by cipchk** [comment]
fixed by `14.0.1`

**Comment by rqx110** [comment]
also need add `postcss-less` package
